import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:photo_manager/photo_manager.dart';
import 'package:provider/provider.dart';
import 'package:share_plus/share_plus.dart';
import '../providers/gallery_refresh_notifier.dart';
import '../services/gallery_service.dart';

/// Gallery screen displaying recent images generated by the app.
///
/// Features:
/// - Displays up to 100 most recent images from the Outfiti album
/// - Responsive grid layout (2-3 columns based on screen width)
/// - Lazy-loaded thumbnails for optimal performance
/// - Tap to view full-screen with pinch-to-zoom
/// - Long-press to share via system share sheet
/// - Handles permission states gracefully
/// - Shows friendly empty state when no images exist
class GalleryScreen extends StatefulWidget {
  const GalleryScreen({super.key});

  @override
  State<GalleryScreen> createState() => _GalleryScreenState();
}

class _GalleryScreenState extends State<GalleryScreen> {
  final GalleryService _galleryService = GalleryService();

  List<AssetEntity> _images = [];
  bool _isLoading = true;
  bool _hasPermission = false;

  /// Tracks the last refresh count to detect when a new image was saved
  int _lastRefreshCount = 0;

  @override
  void initState() {
    super.initState();
    _loadImages();
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    // Listen for gallery refresh events (triggered when images are saved)
    final refreshNotifier = context.watch<GalleryRefreshNotifier>();
    if (refreshNotifier.refreshCount > _lastRefreshCount) {
      _lastRefreshCount = refreshNotifier.refreshCount;
      // Only reload if we already have permission (avoid re-requesting on first load)
      if (_hasPermission && !_isLoading) {
        _loadImages();
      }
    }
  }

  Future<void> _loadImages() async {
    setState(() {
      _isLoading = true;
    });

    // Check/request permission
    final granted = await _galleryService.requestPermission();

    if (!mounted) return;

    if (!granted) {
      setState(() {
        _isLoading = false;
        _hasPermission = false;
      });
      return;
    }

    // Fetch images
    final images = await _galleryService.fetchRecentImages();

    if (!mounted) return;

    setState(() {
      _images = images;
      _hasPermission = true;
      _isLoading = false;
    });
  }

  void _openFullScreen(AssetEntity asset, int index) {
    Navigator.of(context).push(
      MaterialPageRoute(
        builder: (context) => _FullScreenImageViewer(
          asset: asset,
          galleryService: _galleryService,
        ),
      ),
    );
  }

  Future<void> _shareImage(AssetEntity asset) async {
    final file = await _galleryService.getFullImage(asset);
    if (file != null && mounted) {
      // Get the screen size for iPad popover positioning
      final box = context.findRenderObject() as RenderBox?;
      final sharePositionOrigin = box != null
          ? box.localToGlobal(Offset.zero) & box.size
          : null;

      await Share.shareXFiles(
        [XFile(file.path)],
        text: 'Check out my outfit created by Outfiti! https://apps.apple.com/us/app/outfiti/id6757889234',
        sharePositionOrigin: sharePositionOrigin,
      );
    }
  }

  void _navigateToTryNewStyle() {
    // Navigate to the first tab (Hair Try On)
    // Since we're in the navigation stack, we need to find the parent navigator
    final navigator = Navigator.of(context, rootNavigator: true);
    navigator.popUntil((route) => route.isFirst);
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    if (_isLoading) {
      return _buildLoadingState(colorScheme);
    }

    if (!_hasPermission) {
      return _buildPermissionDeniedState(colorScheme);
    }

    if (_images.isEmpty) {
      return _buildEmptyState(colorScheme);
    }

    return _buildGalleryGrid(colorScheme);
  }

  Widget _buildLoadingState(ColorScheme colorScheme) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          CircularProgressIndicator(
            color: colorScheme.secondary,
          ),
          const SizedBox(height: 16),
          Text(
            'Loading your creations...',
            style: TextStyle(
              color: colorScheme.onSurface.withValues(alpha: 0.7),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildPermissionDeniedState(ColorScheme colorScheme) {
    return Padding(
      padding: const EdgeInsets.all(32),
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.photo_library_outlined,
              size: 80,
              color: colorScheme.outline.withValues(alpha: 0.5),
            ),
            const SizedBox(height: 24),
            Text(
              'Photo Access Required',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.w600,
                color: colorScheme.onSurface,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 12),
            Text(
              'To view your saved outfits, please grant access to your photo library.',
              style: TextStyle(
                fontSize: 14,
                color: colorScheme.outline,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 32),
            FilledButton(
              onPressed: () async {
                await _galleryService.openSettings();
              },
              style: FilledButton.styleFrom(
                minimumSize: const Size.fromHeight(56),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(16),
                ),
              ),
              child: const Text('Open Settings'),
            ),
            const SizedBox(height: 12),
            OutlinedButton(
              onPressed: _loadImages,
              style: OutlinedButton.styleFrom(
                minimumSize: const Size.fromHeight(56),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(16),
                ),
              ),
              child: Text(
                'Try Again',
                style: TextStyle(
                  color: colorScheme.secondary,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildEmptyState(ColorScheme colorScheme) {
    return Padding(
      padding: const EdgeInsets.all(32),
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.auto_awesome_outlined,
              size: 80,
              color: colorScheme.secondary.withValues(alpha: 0.6),
            ),
            const SizedBox(height: 24),
            Text(
              'Your outfit creations will appear here',
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.w600,
                color: colorScheme.onSurface,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 12),
            Text(
              'Start experimenting with new outfits and styles. Your saved creations will show up in this gallery.',
              style: TextStyle(
                fontSize: 14,
                color: colorScheme.outline,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 32),
            FilledButton.icon(
              onPressed: _navigateToTryNewStyle,
              icon: const Icon(Icons.add_photo_alternate_outlined),
              label: const Text('Try a new style'),
              style: FilledButton.styleFrom(
                minimumSize: const Size.fromHeight(56),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(16),
                ),
              ),
            ),
          ],
        ).animate().fadeIn(duration: 400.ms).scale(
              begin: const Offset(0.95, 0.95),
              end: const Offset(1.0, 1.0),
              duration: 400.ms,
              curve: Curves.easeOut,
            ),
      ),
    );
  }

  Widget _buildGalleryGrid(ColorScheme colorScheme) {
    return RefreshIndicator(
      onRefresh: _loadImages,
      color: colorScheme.secondary,
      child: LayoutBuilder(
        builder: (context, constraints) {
          // Responsive column count: 3 on wider screens, 2 on narrow screens
          final crossAxisCount = constraints.maxWidth > 400 ? 3 : 2;

          return GridView.builder(
            padding: const EdgeInsets.all(16),
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: crossAxisCount,
              crossAxisSpacing: 12,
              mainAxisSpacing: 12,
              childAspectRatio: 1.0, // Square images
            ),
            itemCount: _images.length,
            itemBuilder: (context, index) {
              return _GalleryImageCard(
                asset: _images[index],
                galleryService: _galleryService,
                onTap: () => _openFullScreen(_images[index], index),
                onLongPress: () => _shareImage(_images[index]),
                index: index,
              );
            },
          );
        },
      ),
    );
  }
}

/// Individual gallery image card with rounded corners and animation
class _GalleryImageCard extends StatefulWidget {
  final AssetEntity asset;
  final GalleryService galleryService;
  final VoidCallback onTap;
  final VoidCallback onLongPress;
  final int index;

  const _GalleryImageCard({
    required this.asset,
    required this.galleryService,
    required this.onTap,
    required this.onLongPress,
    required this.index,
  });

  @override
  State<_GalleryImageCard> createState() => _GalleryImageCardState();
}

class _GalleryImageCardState extends State<_GalleryImageCard> {
  Uint8List? _thumbnail;
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadThumbnail();
  }

  Future<void> _loadThumbnail() async {
    final thumbnail = await widget.galleryService.getThumbnail(widget.asset);
    if (mounted) {
      setState(() {
        _thumbnail = thumbnail;
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;

    return Material(
      borderRadius: BorderRadius.circular(16),
      clipBehavior: Clip.antiAlias,
      color: colorScheme.surfaceContainerHighest,
      child: InkWell(
        onTap: widget.onTap,
        onLongPress: widget.onLongPress,
        child: _isLoading || _thumbnail == null
            ? Center(
                child: CircularProgressIndicator(
                  strokeWidth: 2,
                  color: colorScheme.secondary.withValues(alpha: 0.5),
                ),
              )
            : Hero(
                tag: 'gallery_image_${widget.asset.id}',
                child: Image.memory(
                  _thumbnail!,
                  fit: BoxFit.cover,
                  width: double.infinity,
                  height: double.infinity,
                ),
              ),
      ),
    )
        .animate()
        .fadeIn(
          duration: 300.ms,
          delay: (50 * widget.index).ms,
          curve: Curves.easeOut,
        )
        .scale(
          begin: const Offset(0.9, 0.9),
          end: const Offset(1.0, 1.0),
          duration: 300.ms,
          delay: (50 * widget.index).ms,
          curve: Curves.easeOut,
        );
  }
}

/// Full-screen image viewer with pinch-to-zoom and share functionality
class _FullScreenImageViewer extends StatefulWidget {
  final AssetEntity asset;
  final GalleryService galleryService;

  const _FullScreenImageViewer({
    required this.asset,
    required this.galleryService,
  });

  @override
  State<_FullScreenImageViewer> createState() => _FullScreenImageViewerState();
}

class _FullScreenImageViewerState extends State<_FullScreenImageViewer> {
  File? _fullImage;
  bool _isLoading = true;
  final TransformationController _transformationController =
      TransformationController();

  @override
  void initState() {
    super.initState();
    _loadFullImage();
  }

  @override
  void dispose() {
    _transformationController.dispose();
    super.dispose();
  }

  Future<void> _loadFullImage() async {
    final file = await widget.galleryService.getFullImage(widget.asset);
    if (mounted) {
      setState(() {
        _fullImage = file;
        _isLoading = false;
      });
    }
  }

  Future<void> _shareImage() async {
    if (_fullImage != null) {
      // Get the screen size for iPad popover positioning
      final box = context.findRenderObject() as RenderBox?;
      final sharePositionOrigin = box != null
          ? box.localToGlobal(Offset.zero) & box.size
          : null;

      await Share.shareXFiles(
        [XFile(_fullImage!.path)],
        text: 'Check out my outfit created by Outfiti! https://apps.apple.com/us/app/outfiti/id6757889234',
        sharePositionOrigin: sharePositionOrigin,
      );
    }
  }

  void _resetZoom() {
    _transformationController.value = Matrix4.identity();
  }

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;

    return Scaffold(
      backgroundColor: Colors.black,
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        backgroundColor: Colors.black.withValues(alpha: 0.5),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () => Navigator.of(context).pop(),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.ios_share, color: Colors.white),
            onPressed: _shareImage,
            tooltip: 'Share',
          ),
          IconButton(
            icon: const Icon(Icons.zoom_out_map, color: Colors.white),
            onPressed: _resetZoom,
            tooltip: 'Reset zoom',
          ),
        ],
      ),
      body: _isLoading
          ? Center(
              child: CircularProgressIndicator(
                color: colorScheme.secondary,
              ),
            )
          : _fullImage == null
              ? Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(
                        Icons.error_outline,
                        size: 48,
                        color: Colors.white.withValues(alpha: 0.5),
                      ),
                      const SizedBox(height: 16),
                      const Text(
                        'Failed to load image',
                        style: TextStyle(color: Colors.white70),
                      ),
                    ],
                  ),
                )
              : GestureDetector(
                  onDoubleTap: _resetZoom,
                  child: InteractiveViewer(
                    transformationController: _transformationController,
                    minScale: 0.5,
                    maxScale: 4.0,
                    child: Center(
                      child: Hero(
                        tag: 'gallery_image_${widget.asset.id}',
                        child: Image.file(
                          _fullImage!,
                          fit: BoxFit.contain,
                        ),
                      ),
                    ),
                  ),
                ),
    );
  }
}
